apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-social
spec:
  selector:
    matchLabels:
      app: repo-social
  replicas: 1
  template:
    metadata:
      labels:
        app: repo-social
    spec:
      imagePullSecrets:
        - name: info8-pull-secret
      containers:
      - name: repo-social
        image: registry.cri.epita.fr/ing/majeures/tc/info/student/2026/2025-epitweet-tinyx-18/repo-social:1.0.3
        ports:
        - name: http
          containerPort: 8082
