apiVersion: v1
kind: Service
metadata:
  name: repo-social
  namespace: info8
  labels:
    name: repo-social
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8082
      targetPort: 8082
  selector:
    app: repo-social
