---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: info8
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: "elasticsearch"
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: increase-vm-max-map-count
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data/elasticsearch"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /data/elasticsearch
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
          env:
            - name: discovery.type
              value: "single-node"
            - name: cluster.name
              value: "es-cluster"
            - name: bootstrap.memory_lock
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: path.data
              value: "/data/elasticsearch"
            - name: xpack.security.enabled
              value: "false"
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-admin-credentials
                  key: ELASTICSEARCH_USERNAME
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-admin-credentials
                  key: ELASTICSEARCH_PASSWORD
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /data/elasticsearch
            - name: init-scripts
              mountPath: /usr/share/elasticsearch/config/init.sh
              subPath: init.sh
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "/usr/share/elasticsearch/config/init.sh"]
      volumes:
        - name: init-scripts
          configMap:
            name: elasticsearch-initdb
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
