apiVersion: v1
kind: Service
metadata:
  name: srvc-user-timeline
  namespace: info8
  labels:
    name: srvc-user-timeline
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8084
      targetPort: 8084
  selector:
    app: srvc-user-timeline
