---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: info8
spec:
  ports:
    - port: 7474
      name: http
    - port: 7687
      name: bolt
  clusterIP: None
  selector:
    app: neo4j
