---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: info8
spec:
  selector:
    matchLabels:
      app: neo4j
  serviceName: "neo4j"
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:4.4
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j-admin-credentials
                  key: NEO4J_AUTH
          volumeMounts:
            - name: neo4j-data
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
