apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvc-search
spec:
  selector:
    matchLabels:
      app: srvc-search
  replicas: 1
  template:
    metadata:
      labels:
        app: srvc-search
    spec:
      imagePullSecrets:
        - name: info8-pull-secret
      containers:
      - name: srvc-search
        image: registry.cri.epita.fr/ing/majeures/tc/info/student/2026/2025-epitweet-tinyx-18/srvc-search:1.0.3
        ports:
        - name: http
          containerPort: 8083
