---
apiVersion: v1
kind: Secret
metadata:
  name: sundaland-mongodb-credentials
  namespace: info8
stringData:
  SUNDALAND_MONGODB_USER: user1
  SUNDALAND_MONGODB_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: info8-pull-secret
  namespace: info8
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "bWF0dGhpZXUudGlybG95OmNzc2Fyd1IyRnhCNmpndGNZX1hj"
          }
      }
    }
type: kubernetes.io/dockerconfigjson
