apiVersion: v1
kind: Service
metadata:
  name: repo-post
  namespace: info8
  labels:
    name: repo-post
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081
  selector:
    app: repo-post
